sqlcmd -S SRV11 -U sa -P dotnet -t 0 -i _PURGE_DATA.sql
sqlcmd -S SRV11 -U sa -P dotnet -t 0 -i Perusahaan.sql
sqlcmd -S SRV11 -U sa -P dotnet -t 0 -i Propinsi.sql
sqlcmd -S SRV11 -U sa -P dotnet -t 0 -i Kota.sql
sqlcmd -S SRV11 -U sa -P dotnet -t 0 -i KelompokBarang.sql
sqlcmd -S SRV11 -U sa -P dotnet -t 0 -i Stock.sql
sqlcmd -S SRV11 -U sa -P dotnet -t 0 -i StockNamaImport.sql
sqlcmd -S SRV11 -U sa -P dotnet -t 0 -i Toko.sql
sqlcmd -S SRV11 -U sa -P dotnet -t 0 -i TokoStatus.sql
sqlcmd -S SRV11 -U sa -P dotnet -t 0 -i TokoMasalah.sql
sqlcmd -S SRV11 -U sa -P dotnet -t 0 -i Toko00.sql
sqlcmd -S SRV11 -U sa -P dotnet -t 0 -i SparePart.sql
sqlcmd -S SRV11 -U sa -P dotnet -t 0 -i HistoryHPPA.sql
sqlcmd -S SRV11 -U sa -P dotnet -t 0 -i HrgBMKStock.sql
sqlcmd -S SRV11 -U sa -P dotnet -t 0 -i HrgBMKStock0.sql
sqlcmd -S SRV11 -U sa -P dotnet -t 0 -i HrgBMKStock2.sql
sqlcmd -S SRV11 -U sa -P dotnet -t 0 -i HrgBMKKelompokBarang.sql
sqlcmd -S SRV11 -U sa -P dotnet -t 0 -i HasilOpname.sql
sqlcmd -S SRV11 -U sa -P dotnet -t 0 -i KursHargaJualBarang.sql
sqlcmd -S SRV11 -U sa -P dotnet -t 0 -i Sales.sql
sqlcmd -S SRV11 -U sa -P dotnet -t 0 -i SalesmanRiwayat.sql

sqlcmd -S SRV11 -U sa -P dotnet -t 0 -i RekapStock.sql
sqlcmd -S SRV11 -U sa -P dotnet -t 0 -i MutasiHeader.sql
sqlcmd -S SRV11 -U sa -P dotnet -t 0 -i MutasiDetail.sql
sqlcmd -S SRV11 -U sa -P dotnet -t 0 -i BiayaPerSupplier.sql
sqlcmd -S SRV11 -U sa -P dotnet -t 0 -i HargaPersediaanHeader.sql
sqlcmd -S SRV11 -U sa -P dotnet -t 0 -i HargaPersediaanDetail.sql
sqlcmd -S SRV11 -U sa -P dotnet -t 0 -i HargaPersediaanAutoHarga.sql
sqlcmd -S SRV11 -U sa -P dotnet -t 0 -i StockSalesHeader.sql
sqlcmd -S SRV11 -U sa -P dotnet -t 0 -i StockSalesDetail.sql
sqlcmd -S SRV11 -U sa -P dotnet -t 0 -i StockSalesSubDetail.sql

sqlcmd -S SRV11 -U sa -P dotnet -t 0 -i POHeader.sql
sqlcmd -S SRV11 -U sa -P dotnet -t 0 -i PODetail.sql
sqlcmd -S SRV11 -U sa -P dotnet -t 0 -i PLHeader.sql
sqlcmd -S SRV11 -U sa -P dotnet -t 0 -i PLHeaderLokal.sql
sqlcmd -S SRV11 -U sa -P dotnet -t 0 -i PLDetail.sql
sqlcmd -S SRV11 -U sa -P dotnet -t 0 -i PLDetailLokal.sql
sqlcmd -S SRV11 -U sa -P dotnet -t 0 -i BLHeader.sql
sqlcmd -S SRV11 -U sa -P dotnet -t 0 -i KoreksiPB.sql
sqlcmd -S SRV11 -U sa -P dotnet -t 0 -i KoreksiPBL.sql
sqlcmd -S SRV11 -U sa -P dotnet -t 0 -i RBHeader.sql
sqlcmd -S SRV11 -U sa -P dotnet -t 0 -i RBDetail.sql
sqlcmd -S SRV11 -U sa -P dotnet -t 0 -i RBDetailLokal.sql
sqlcmd -S SRV11 -U sa -P dotnet -t 0 -i KoreksiRB.sql
sqlcmd -S SRV11 -U sa -P dotnet -t 0 -i KoreksiRBLokal.sql

sqlcmd -S SRV11 -U sa -P dotnet -t 0 -i AccHargaHeader.sql
sqlcmd -S SRV11 -U sa -P dotnet -t 0 -i AccHargaDetail.sql
sqlcmd -S SRV11 -U sa -P dotnet -t 0 -i PenjualanHeader.sql
sqlcmd -S SRV11 -U sa -P dotnet -t 0 -i PenjualanRequestCabang.sql
sqlcmd -S SRV11 -U sa -P dotnet -t 0 -i PenjualanDetail.sql
sqlcmd -S SRV11 -U sa -P dotnet -t 0 -i CheckerMapping.sql
sqlcmd -S SRV11 -U sa -P dotnet -t 0 -i SJHeader.sql
sqlcmd -S SRV11 -U sa -P dotnet -t 0 -i SJDetail.sql
sqlcmd -S SRV11 -U sa -P dotnet -t 0 -i SJTitipan.sql
sqlcmd -S SRV11 -U sa -P dotnet -t 0 -i KoreksiPenjualan.sql
sqlcmd -S SRV11 -U sa -P dotnet -t 0 -i RJHeader.sql
sqlcmd -S SRV11 -U sa -P dotnet -t 0 -i RJDetail.sql
sqlcmd -S SRV11 -U sa -P dotnet -t 0 -i KoreksiRJ.sql
pause