DELETE FROM ISAPalurTradingDb02.dbo.RJDetail
DELETE FROM ISAPalurTradingDb02.dbo.RJHeader
DELETE FROM ISAPalurTradingDb02.dbo.KoreksiPenjualan
DELETE FROM ISAPalurTradingDb02.dbo.SJTitipan
DELETE FROM ISAPalurTradingDb02.dbo.SJDetail
DELETE FROM ISAPalurTradingDb02.dbo.SJHeader
DELETE FROM ISAPalurTradingDb02.dbo.CheckerMapping
DELETE FROM ISAPalurTradingDb02.dbo.PenjualanDetail
DELETE FROM ISAPalurTradingDb02.dbo.PenjualanHeader
DELETE FROM ISAPalurTradingDb02.dbo.PenjualanRequestCabang
DELETE FROM ISAPalurTradingDb02.dbo.AccHargaDetail
DELETE FROM ISAPalurTradingDb02.dbo.AccHargaHeader
DELETE FROM ISAPalurTradingDb02.dbo.KoreksiRB
DELETE FROM ISAPalurTradingDb02.dbo.KoreksiRBLokal
DELETE FROM ISAPalurTradingDb02.dbo.RBDetail
DELETE FROM ISAPalurTradingDb02.dbo.RBDetailLokal
DELETE FROM ISAPalurTradingDb02.dbo.RBHeader
DELETE FROM ISAPalurTradingDb02.dbo.KoreksiPB
DELETE FROM ISAPalurTradingDb02.dbo.KoreksiPBL
DELETE FROM ISAPalurTradingDb02.dbo.BLHeader
DELETE FROM ISAPalurTradingDb02.dbo.PLDetail
DELETE FROM ISAPalurTradingDb02.dbo.PLDetailLokal
DELETE FROM ISAPalurTradingDb02.dbo.PLHeader
DELETE FROM ISAPalurTradingDb02.dbo.PLHeaderLokal
DELETE FROM ISAPalurTradingDb02.dbo.POUangMuka
DELETE FROM ISAPalurTradingDb02.dbo.PODetail
DELETE FROM ISAPalurTradingDb02.dbo.PODetailLokal
DELETE FROM ISAPalurTradingDb02.dbo.POHeader
DELETE FROM ISAPalurTradingDb02.dbo.POHeaderLokal
DELETE FROM ISAPalurTradingDb02.dbo.HargaPersediaanAutoHarga
DELETE FROM ISAPalurTradingDb02.dbo.HargaPersediaanDetail
DELETE FROM ISAPalurTradingDb02.dbo.HargaPersediaanHeader
DELETE FROM ISAPalurTradingDb02.dbo.StockSalesSubDetail
DELETE FROM ISAPalurTradingDb02.dbo.StockSalesDetail
DELETE FROM ISAPalurTradingDb02.dbo.StockSalesHeader
DELETE FROM ISAPalurTradingDb02.dbo.BiayaPerSupplier
DELETE FROM ISAPalurTradingDb02.dbo.MutasiDetail
DELETE FROM ISAPalurTradingDb02.dbo.MutasiHeader
DELETE FROM ISAPalurTradingDb02.dbo.RekapStock
DELETE FROM ISAPalurTradingDb02.dbo.SalesmanRiwayat
DELETE FROM ISAPalurTradingDb02.dbo.Salesman
DELETE FROM ISAPalurTradingDb02.dbo.OpnameDetail
DELETE FROM ISAPalurTradingDb02.dbo.OpnameFormHeader
DELETE FROM ISAPalurTradingDb02.dbo.OpnameMaster
DELETE FROM ISAPalurTradingDb02.dbo.KursHargaJualBarang
DELETE FROM ISAPalurTradingDb02.dbo.HasilOpname
DELETE FROM ISAPalurTradingDb02.dbo.HrgBMKKelompokBarangHistory
DELETE FROM ISAPalurTradingDb02.dbo.HrgBMKKelompokBarang
DELETE FROM ISAPalurTradingDb02.dbo.HrgBMKStock2History
DELETE FROM ISAPalurTradingDb02.dbo.HrgBMKStock0History
DELETE FROM ISAPalurTradingDb02.dbo.HrgBMKStockHistory
DELETE FROM ISAPalurTradingDb02.dbo.HrgBMKStock2
DELETE FROM ISAPalurTradingDb02.dbo.HrgBMKStock0
DELETE FROM ISAPalurTradingDb02.dbo.HrgBMKStock
DELETE FROM ISAPalurTradingDb02.dbo.HistoryHPPA
DELETE FROM ISAPalurTradingDb02.dbo.HutangPembelian
DELETE FROM ISAPalurTradingDb02.dbo.DeletedHistory
DELETE FROM ISAPalurTradingDb02.dbo.ErrorLog
DELETE FROM ISAPalurTradingDb02.dbo.ErrorTrigger
DELETE FROM ISAPalurTradingDb02.dbo.SparePart
DELETE FROM ISAPalurTradingDb02.dbo.Toko00
DELETE FROM ISAPalurTradingDb02.dbo.TokoMasalah
DELETE FROM ISAPalurTradingDb02.dbo.TokoStatus
DELETE FROM ISAPalurTradingDb02.dbo.Toko
DELETE FROM ISAPalurTradingDb02.dbo.StockNamaImport
DELETE FROM ISAPalurTradingDb02.dbo.Stock
DELETE FROM ISAPalurTradingDb02.dbo.KelompokBarang
DELETE FROM ISAPalurTradingDb02.dbo.Kota
DELETE FROM ISAPalurTradingDb02.dbo.Propinsi
DELETE FROM ISAPalurTradingDb02.dbo.Perusahaan